### ISSUE TITLE
yarn dev 报错 [HPM] Missing "target" option.

### ISSUE THREAD

**Issue by Jsmond2016** [Haixiang6123/refer-me#51]
作者你好，想学习下你的项目，发现启动报错，即使删除 node_modules 重装依然无法解决，请问可以给出相关解决方案吗？感谢~

![error](https://i.loli.net/2020/08/30/jh8tQZXm4rxOUak.png)

**Comment by haixiangyan** [comment]
感谢提醒，应该是 @nuxtjs/proxy 最近升级了写法，在 package.json 里面改成如下即可：

```
    proxy: {
        target: `${process.env.PROXY_BASE_URL}/api`
    },
```

目前已 push 到 dev 分支。

ps: 
因为之前写这个项目只想着自己使用，所以没有写太多的关于本地开发的事情。

如果想本地跑的话需要先

```bash
yarn mock-server
```

再 

```bash
yarn dev
```

**Comment by Jsmond2016** [comment]
好的，感谢作者~
